---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list: recipe[fake::default]
    attributes:
